### ISSUE TITLE
Root extension name create loading error

### ISSUE THREAD

**Issue by M-Rick** [mkoenigb/OpenTripPlannerPlugin#3]
**Describe the bug**
When installing the extension from the ZIP file, it will create an error.

```
Impossible de charger l'extension 'OpenTripPlannerPlugin-1.0' 

ModuleNotFoundError: No module named 'OpenTripPlannerPlugin-1' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'OpenTripPlannerPlugin-1'


Version de Python : 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Version de QGIS : 3.22.3-Białowieża Białowieża, 1628765ec7 

Chemin Python :
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/road_slope_calculator
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/dms_2_deg
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mobilityareas
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geo_sim_processing
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/clusterpoints
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Users/aymeric/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/rvt-qgis
```

**To Reproduce**
Go to the extension manager and install the OpenTripPlannerPlugin fro ma ZIP archive.

**Expected behavior**
To fix the problem, the folder in the archive shouldn't have the version in its naming.
It is necessary to rename the folder `OpenTripPlannerPlugin` in the QGIS profile extension folder and it works.

**Screenshots**

![Capture d’écran 2022-02-06 à 19 38 46](https://user-images.githubusercontent.com/2520948/152696311-3d12094f-0468-4f60-8137-f200f5ee5c97.png)

![Capture d’écran 2022-02-06 à 19 42 00](https://user-images.githubusercontent.com/2520948/152696316-c78546e9-5f6f-45cd-81c6-c89c5dffcd38.png)

**Desktop (please complete the following information):**
Any

**Comment by mkoenigb** [comment]
@M-Rick You need to rename the PlugIn-folder to "OpenTripPlannerPlugin":

![grafik](https://user-images.githubusercontent.com/70903958/152697061-73427df0-4fdf-492c-92f4-ac371620dbb7.png)

You can also name it e.g. "OpenTripPlannerPlugin-101" if you want the version number in it, but having dots in the folder name will raise this error.

**Comment by mkoenigb** [comment]
I have renamed the release-tag in the repository to "1-0-1" so GitHub will not autogenerate a folder having dots in it.
